name: ScheduleJob by Atul

on:
  schedule:
    - cron: '00 01 * * *'     # 5:22 PM IST
  workflow_dispatch:          # manual trigger
    inputs:
      name:
        description: 'Name'
        type: string
        required: true
        default: 'defaultValue'
      lastname:
        description: 'LastName'
        type: string
        default: 'defaultValue'

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Print Full Name
        run: echo "My name is ${{ inputs.name }} ${{ inputs.lastname }}"
    
