name: Testing Github Action

on:
  schedule:
    - '46 10 * * *'   # 10:46 UTC = 16:16 IST
  workflow_dispatch:         # still allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the project
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures 'test' runs after 'build'
    steps:
      - name: Run tests
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures 'deploy' runs after 'test'
    steps:
      - name: Deploy the app
        run: echo "Deploying..."
