name: ScheduleJob by Atul

on:
  schedule:
    - cron: '00 01 * * *'     # 5:22 PM IST
  workflow_dispatch:          # manual trigger
    inputs:
      name:
        description: 'Name'
        type: string
        required: true
        default: 'defaultName'
      lastname:
        description: 'LastName'
        type: string
        default: 'defaultLastName'
      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female
      testflag:
        description: 'Test Flag'
        type: boolean

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Print Full Name
        run: echo "My name is ${{ inputs.name }} ${{ inputs.lastname }}"

      - name: Gender
        run: echo "Gender is ${{ inputs.gender }}"

  executeAutomation:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Automation
        run: echo "Executing automation only printing this statement"

        
    
