name: ScheduleJob by Atul

on:
  schedule:
    - cron: '00 01 * * *'     # 5:22 PM IST
  workflow_dispatch:          # manual trigger
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'defaultValue'

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: PrintName
        run: echo "My name is ${{ inputs.name }}"
    
