name: Github Action by Atul

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'defaultValue'

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"
    
