name: Every 5 Minutes Cron

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes UTC
  workflow_dispatch:         # optional manual trigger

jobs:
  repeat-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "UTC time:"
          date -u
          echo "IST time:"
          TZ=Asia/Kolkata date
