name: Testing Github Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the project
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures 'test' runs after 'build'
    steps:
      - name: Run tests
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures 'deploy' runs after 'test'
    steps:
      - name: Deploy the app
        run: echo "Deploying..."
