name: Cron Test

on:
  schedule:
    - cron: '10 12 * * *'
  workflow_dispatch:

jobs:
  say-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print UTC time
        run: date -u
      - name: Print IST time
        run: TZ=Asia/Kolkata date
